services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studylink_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace # 현재 폴더를 컨테이너의 /workspace와 동기화
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: studylink_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: 